"""Per-tenant model API key resolution (BYOK, §9 + §12.3).

`resolve_model_key` reads the unified credentials framework's core-owned
`{canonical}_api_key` credential type (Task 14, `oc8.credentials.core_types`)
rather than a raw named secret -- `ProviderCard`'s `<CredentialPicker>` (the
completion key connect flow) writes a `Credential` row, not a bare
`model/{canonical}/api_key` secret, so this must read the same shape it
writes. Convention (not an enforced invariant -- there is no DB constraint
or app-level check) is that a provider has at most one such credential: the
UI encourages this, but `CredentialPicker`'s always-visible "Create new"
button means a "Change key"/rotate flow can leave a tenant with TWO. When
that happens, "first" must mean the same thing here as it does in
`oc8.credentials.service.list_credentials` (ordered by `name`, which is what
`GET /credentials?type=...` returns and what `ProviderCard` shows as
"bound") -- ordering by `created_at` instead would let this function silently
keep using a stale, non-"bound" key after a rotation. A missing key is the
fallback signal (returns None) -- only a misconfigured store fails loud,
because a broken store must never silently bill the platform key.
"""

from __future__ import annotations

import json
import logging
import uuid

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from oc8 import models as m
from oc8.credentials.service import (
    CredentialFieldNotSet,
    CredentialNotFound,
    resolve_credential_field,
)
from oc8.modelrouter.registry import canonical_provider
from oc8.oauth.errors import OAuthError
from oc8.oauth.tokens import get_access_token

logger = logging.getLogger(__name__)


def model_key_ref(canonical: str) -> str:
    return f"model/{canonical}/api_key"


def model_admin_key_ref(canonical: str) -> str:
    """A separate, more-privileged credential from model_key_ref()'s
    completion key -- an Anthropic/OpenAI Admin or Org API key, generated by
    an org owner in the provider's own console, used ONLY for the optional
    cost-reconciliation fetch (Cost Center design, 2026-08-19 spec Part C).
    Storage reuses the existing generic /secrets API -- there is no dedicated
    admin-key endpoint."""
    return f"model/{canonical}/admin_key"


async def _bound_credential(
    db: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    canonical: str,
    credential_id: uuid.UUID | None = None,
) -> m.Credential | None:
    """The `{canonical}_api_key` credential `resolve_model_key`/
    `resolve_model_base_url` both treat as "bound" for this call -- same row,
    same rule, so a key lookup and a base_url lookup for the same provider
    can never disagree about which credential is the active one.

    `credential_id` (set from a specific `ModelConfig.credential_id`, when
    that ModelConfig has bound one -- lets a tenant run multiple accounts of
    one provider, one per ModelConfig) always wins when given: a row that no
    longer exists or belongs to a different tenant returns None outright,
    never silently falling back to the tenant-wide pick below -- an
    explicitly bound credential going missing must read as "no usable key",
    same as any other missing-key case, not as licence to guess a different
    one. With no `credential_id`, falls back to the tenant-wide convention:
    the first credential of this type, ordered by `name` to match
    `list_credentials`/`GET /credentials?type=...`/`ProviderCard`'s own
    "bound" pick exactly."""
    if credential_id is not None:
        row = await db.get(m.Credential, credential_id)
        if row is None or row.tenant_id != tenant_id:
            return None
        return row
    return (
        await db.execute(
            select(m.Credential)
            .where(
                m.Credential.tenant_id == tenant_id,
                m.Credential.credential_type == f"{canonical}_api_key",
            )
            .order_by(m.Credential.name)
            .limit(1)
        )
    ).scalar_one_or_none()


async def _subscription_access_token(
    db: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    oauth_connection_id: object,
    product: str,
) -> tuple[str, uuid.UUID] | None:
    """Live access token for a subscription credential, or None.

    A missing pointer, a dead connection, or a failed refresh is the same
    answer as a missing API key: fall through the model chain. Letting
    ``OAuthError`` escape would tear the chain down, because
    ``oc8.modelrouter.fallback`` calls ``resolve_model_key`` outside its
    own try/except.
    """
    if not isinstance(oauth_connection_id, str) or not oauth_connection_id:
        return None
    try:
        connection_id = uuid.UUID(oauth_connection_id)
    except ValueError:
        return None
    try:
        access_token = await get_access_token(db, tenant_id=tenant_id, connection_id=connection_id)
    except OAuthError:
        logger.warning(
            "%s subscription connection %s cannot produce an access token; "
            "treating this model as having no key so the fallback chain continues",
            product,
            connection_id,
            exc_info=True,
        )
        return None
    return access_token, connection_id


async def resolve_model_key(
    db: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    provider: str,
    credential_id: uuid.UUID | None = None,
) -> str | None:
    """The tenant's own key for `provider`, or None to fall back to the platform
    env key. Providers with no key concept (ollama) and unknown providers return
    None. `SecretStoreUnavailable` propagates."""
    canonical = canonical_provider(provider)
    if canonical is None or canonical == "ollama":
        return None
    row = await _bound_credential(
        db, tenant_id=tenant_id, canonical=canonical, credential_id=credential_id
    )
    if row is None:
        return None
    if row.credential_type in ("openai_chatgpt_subscription", "xai_grok_subscription"):
        # No `api_key` field on these credential types -- each is a pointer
        # to an OAuthConnection. Resolve the live token and return early:
        # the secret-store field lookup below raises CredentialFieldNotSet
        # for every row of these types.
        resolved = await _subscription_access_token(
            db,
            tenant_id=tenant_id,
            oauth_connection_id=row.field_values.get("oauth_connection_id"),
            product="Grok" if row.credential_type == "xai_grok_subscription" else "ChatGPT",
        )
        if resolved is None:
            return None
        access_token, connection_id = resolved
        if row.credential_type == "xai_grok_subscription":
            # The Grok proxy wants the bearer token itself.
            return access_token
        conn = await db.get(m.OAuthConnection, connection_id)
        account_id = (conn.provider_metadata or {}).get("chatgpt_account_id") if conn else None
        return json.dumps({"access_token": access_token, "account_id": account_id})
    try:
        return await resolve_credential_field(
            db, tenant_id=tenant_id, credential_id=row.id, field_key="api_key"
        )
    except (CredentialNotFound, CredentialFieldNotSet):
        # Either failure mode means the same thing to this function's own
        # caller: no usable tenant key, fall back to the platform key. Unlike
        # `SourceAuthContext.credential()`/`configure_plugin`'s credential-kind
        # branch, there is no operator-facing error surface here worth
        # distinguishing the two for.
        return None


async def resolve_model_base_url(
    db: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    provider: str,
    credential_id: uuid.UUID | None = None,
) -> str | None:
    """The tenant's own server address for `provider` (currently meaningful
    only for `openai_compatible` -- see `oc8.credentials.core_types`), or
    None if unset. Unlike `api_key`, `base_url` is a non-secret field: it
    lives directly on the `Credential` row's `field_values`, so this needs
    no secret-store round trip once the row is fetched."""
    canonical = canonical_provider(provider)
    if canonical is None or canonical == "ollama":
        return None
    row = await _bound_credential(
        db, tenant_id=tenant_id, canonical=canonical, credential_id=credential_id
    )
    if row is None:
        return None
    value = (row.field_values or {}).get("base_url")
    return str(value) if value else None
